project:
  type: book
  output-dir: docs
  render: 
    - "*.qmd"

toc: true
toc-location: right

number-sections: true

license: "CC BY-NC-SA"
code-block-border-left: true
code-line-numbers: true
lang: fr-FR

date-modified: last-modified
date-format: "ddd D MMM YYYY"
date: 2024/06/19

reference-location: margin
citation-location: margin
book:
  title: "Décortiquer l'EuroMillions"
  page-footer: "Merci à [Git](https://git-scm.com/), [Github](https://github.com/), [Quarto](https://quarto.org/), [RStudio Desktop](https://posit.co/download/rstudio-desktop/), [R](https://cran.rstudio.com/) et [Wikipédia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal)"
  
  chapters:
    - index.qmd
    - import.qmd
    - compter.qmd
  appendices: 
    - part: Références
      chapters: 
        - references.qmd
    - part: Aide
      chapters: 
        - pluck.qmd
        - mod_pluck.qmd
        - attr_getter.qmd
        - ggplot2.qmd
        - NOTES.qmd
    - part: "Chloé et moi"
      chapters:
        - chloe-001.qmd

bibliography: references.bib

format:
  html:
    fontsize: 1.20em
    theme: 
      dark: darkly
      light: flatly
    highlight-style: ayu
    grid: 
      sidebar-width: 250px
      margin-width: 260px
      body-width: 910px
      gutter-width: 1em
    



