project:
  type: book
  output-dir: docs
  render: 
    - "*.qmd"

toc: true
toc-location: right

number-sections: true

lang: fr-FR

date-modified: last-modified
date-format: "ddd D MMM YYYY"
date: 2024/06/19

reference-location: margin
citation-location: margin
book:
  title: "Décortiquer l'EuroMillions"
  
  chapters:
    - index.qmd
    - import.qmd
  appendices: 
    - part: Références
      chapters: 
        - references.qmd
    - part: Perso
      chapters: 
        - NOTES.qmd
        - chloe-001.qmd

bibliography: references.bib

format:
  html:
    fontsize: 1.20em
    theme: 
      dark: darkly
      light: flatly
    highlight-style: ayu
    grid: 
      sidebar-width: 250px
      margin-width: 260px
      body-width: 910px
      gutter-width: 0.15em
    



